name: Sippanat Samroeng
favicon: null
layout_spectrum: 0.9882600805722177
typography_spectrum: 0.42178604379296303
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.125
  lightness: 0.7745594242587686
  saturation: 0.16913826181553304
  rhythmicContrast: 0.5984798083081841
purpose: []
